# @package _global_

defaults:
  - _self_
  - data: mnist # choose datamodule with `test_dataloader()` for evaluation
  - model: mnist
  - logger: csv
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

model_name: "MNIST_SimpleDenseNet"
task_name: "predict"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
